[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
LoggingExtras = "e6f89c97-d47a-5376-807f-9c37f3926c36"
Molly = "aa0f7f06-fcc0-5ec4-a7f3-a573f33f9c4c"
PDMK4MC = "e4c8b4d2-5072-4abd-9b0d-7efcb1a2c66b"
ParticleMeshEwald = "cd47a632-4c33-49da-880f-bcc568aa1a40"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[sources]
Molly = {path = "/mnt/home/xgao1/codes/Molly.jl/"}
PDMK4MC = {path = "/mnt/home/xgao1/codes/PDMK4MC/julia/"}
ParticleMeshEwald = {path = "/mnt/home/xgao1/codes/ParticleMeshEwald.jl/"}

[extras]
MPIPreferences = "3da0fdf6-3ccc-4f1b-acd9-58baa6c99267"
