[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MPIPreferences = "3da0fdf6-3ccc-4f1b-acd9-58baa6c99267"
PDMK4MC = "e4c8b4d2-5072-4abd-9b0d-7efcb1a2c66b"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[extras]
MPIPreferences = "3da0fdf6-3ccc-4f1b-acd9-58baa6c99267"
